import { CategoryIdSchema } from "../schemas"
import { defineCatalogCategory, PROGRESSION_RIR, STOP_SIGNALS } from "./lower-catalog.private"

const instructions = [
  "몸통 긴장을 유지하고 허리가 과하게 뜨거나 꺾이지 않게 한다.",
  "호흡을 참지 않고 통제된 속도로 수행한다.",
  "행잉 단계는 철봉 상태를 확인한 뒤 발 보조부터 하중을 건다.",
] as const

const mistakes = [
  "허리 반동으로 반복 수를 늘림",
  "목과 어깨에 과하게 힘을 줌",
  "철봉 하중 확인 없이 매달림",
] as const

const safety = ["갑작스러운 허리 통증, 저림, 심한 어지럼증이 있으면 해당 운동을 중단한다."] as const

export const core = defineCatalogCategory({
  id: CategoryIdSchema.parse("core"),
  title: "CORE",
  muscles: ["복직근", "복횡근", "복사근", "몸통 안정성"],
  warmup: [
    "Cat-Cow 6회",
    "골반 기울이기 10회",
    "버드독 좌우 5회",
    "행잉 운동 단계라면 발 보조 매달리기 10초 × 1~2회",
  ],
  instructions,
  mistakes,
  stopSignals: STOP_SIGNALS,
  levels: [
    {
      level: 0,
      name: "데드버그",
      targetLabel: "좌우 10회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 10,
        max: 10,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 60,
      assessmentEligible: true,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["팔다리 가동범위를 줄여 허리 뜸을 줄인다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 1,
      name: "플랭크",
      targetLabel: "45초 × 3세트",
      metricRule: { kind: "duration", minSeconds: 45, maxSeconds: 45, sets: 3, laterality: "none" },
      restSeconds: 90,
      assessmentEligible: true,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["무릎 플랭크 또는 더 짧은 시간으로 시작한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 2,
      name: "할로우 바디 홀드",
      targetLabel: "30초 × 3세트",
      metricRule: { kind: "duration", minSeconds: 30, maxSeconds: 30, sets: 3, laterality: "none" },
      restSeconds: 90,
      assessmentEligible: true,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["무릎을 접은 할로우 홀드로 난도를 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 3,
      name: "행잉 니레이즈",
      targetLabel: "10~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 10,
        max: 12,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["문틈철봉"],
      regressions: ["누운 니레이즈 또는 발 보조 행잉으로 돌아간다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 4,
      name: "스트레이트 레그레이즈 진행",
      targetLabel: "8~10회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 10,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["맨몸 또는 문틈철봉"],
      regressions: ["무릎을 더 굽힌 레그레이즈로 범위를 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 5,
      name: "행잉 레그레이즈",
      targetLabel: "8~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 12,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["문틈철봉"],
      regressions: ["행잉 니레이즈 또는 스트레이트 레그레이즈 진행으로 돌아간다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 6,
      name: "푸시업바 Tuck L-sit",
      targetLabel: "20~30초 × 3세트",
      metricRule: { kind: "duration", minSeconds: 20, maxSeconds: 30, sets: 3, laterality: "none" },
      restSeconds: 150,
      assessmentEligible: false,
      promotable: true,
      equipment: ["푸시업바"],
      regressions: ["발끝을 가볍게 바닥에 두고 시간을 줄인다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 7,
      name: "L-sit",
      targetLabel: "20~30초 × 3세트",
      metricRule: { kind: "duration", minSeconds: 20, maxSeconds: 30, sets: 3, laterality: "none" },
      restSeconds: 150,
      assessmentEligible: false,
      promotable: true,
      equipment: ["푸시업바"],
      regressions: ["Tuck L-sit로 다리 길이를 줄인다."],
      instructions,
      mistakes,
      safety,
    },
  ],
} as const)
