import { CategoryIdSchema } from "../schemas"
import { defineCatalogCategory, PROGRESSION_RIR, STOP_SIGNALS } from "./lower-catalog.private"

const instructions = [
  "허리를 숙이기보다 고관절을 접는 느낌으로 엉덩이를 뒤로 보낸다.",
  "덤벨은 몸 가까이 유지한다.",
  "허리가 둥글게 말리기 전 범위에서 멈춘다.",
] as const

const mistakes = [
  "무릎을 스쿼트처럼 많이 굽힘",
  "허리를 둥글게 말아 더 내려감",
  "덤벨이 몸에서 멀어짐",
] as const

const safety = ["갑작스러운 허리 통증이나 저림이 있으면 해당 운동을 중단한다."] as const

export const hinge = defineCatalogCategory({
  id: CategoryIdSchema.parse("hinge"),
  title: "HIP HINGE",
  muscles: ["햄스트링", "둔근", "후면사슬"],
  warmup: [
    "Cat-Cow 6~8회",
    "글루트 브리지 8~10회",
    "맨몸 힙힌지 10회",
    "RDL 단계라면 5kg 덤벨 한 개로 5~8회",
  ],
  instructions,
  mistakes,
  stopSignals: STOP_SIGNALS,
  levels: [
    {
      level: 0,
      name: "맨몸 힙힌지",
      targetLabel: "15회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 15,
        max: 15,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 90,
      assessmentEligible: true,
      promotable: true,
      equipment: ["맨몸", "벽"],
      regressions: ["벽과 거리를 줄여 엉덩이 터치 범위를 줄인다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 1,
      name: "글루트 브리지",
      targetLabel: "15~20회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 15,
        max: 20,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 90,
      assessmentEligible: true,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["상단 정지를 줄이고 반복을 천천히 수행한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 2,
      name: "덤벨 RDL 10kg",
      targetLabel: "12~15회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 12,
        max: 15,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: true,
      promotable: true,
      equipment: ["5kg 덤벨 2개"],
      regressions: ["덤벨 한 개 또는 맨몸 힙힌지로 중량을 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 3,
      name: "3초 하강 RDL",
      targetLabel: "12~15회 × 3세트 · 3초 하강",
      metricRule: {
        kind: "tempoReps",
        min: 12,
        max: 15,
        tempoSeconds: 3,
        sets: 3,
        laterality: "none",
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["5kg 덤벨 2개"],
      regressions: ["일반 덤벨 RDL로 템포 요구를 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 4,
      name: "B-스탠스 RDL",
      targetLabel: "좌우 10~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 10,
        max: 12,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["5kg 덤벨"],
      regressions: ["양발 RDL로 돌아가 좌우 균형을 확보한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 5,
      name: "맨몸 싱글레그 RDL",
      targetLabel: "좌우 8~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 12,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["B-스탠스 RDL로 지지 기반을 넓힌다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 6,
      name: "5kg 싱글레그 RDL",
      targetLabel: "좌우 10~15회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 10,
        max: 15,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["5kg 덤벨 1개"],
      regressions: ["맨몸 싱글레그 RDL로 중량을 뺀다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 7,
      name: "10kg 싱글레그 RDL",
      targetLabel: "좌우 8~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 12,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["5kg 덤벨 2개"],
      regressions: ["5kg 싱글레그 RDL로 중량을 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
  ],
} as const)
