import { GLOBAL_SAFETY_STOP_SIGNALS } from "../content/common"
import { CategoryIdSchema } from "../schemas"
import {
  durationRule,
  formatUpperBodyTargetLabel,
  repsRule,
  tempoRepsRule,
  type UpperBodyCatalog,
  type UpperBodyExerciseLevel,
} from "./upper-body"

const DOORFRAME_BAR_EQUIPMENT = ["문틈철봉", "발 보조를 위한 바닥 지지"] as const
const BAR_CHECKLIST_GATE = { requiresDoorframeBarChecklist: true } as const

const makeLevel = (level: UpperBodyExerciseLevel): UpperBodyExerciseLevel => level

export const PULL_CATEGORY: UpperBodyCatalog = {
  id: CategoryIdSchema.parse("pull"),
  title: "PULL",
  muscles: ["광배근", "등 상부", "이두", "전완"],
  longTermGoal: "매달리기 → 스캐풀라 풀업 → 보조 풀업 → 네거티브 → 친업 → 풀업 → 고급 풀업",
  warmup: [
    "팔 앞뒤 흔들기 10회",
    "벽 슬라이드 8회",
    "견갑골 뒤로 모으기 10회",
    "발을 바닥에 둔 상태로 철봉 잡고 체중 가볍게 싣기 10초 × 2",
    "현재 레벨보다 쉬운 당기기 3~5회",
  ],
  instructions: [
    "반동 없이 시작한다.",
    "어깨가 귀 쪽으로 계속 올라가 있지 않도록 견갑을 조절한다.",
    "턱만 억지로 철봉 위로 넘기지 않는다.",
    "몸을 과하게 젖혀 치팅하지 않는다.",
    "내려올 때도 통제한다.",
  ],
  mistakes: [
    "반동으로 올라가기",
    "어깨가 계속 귀 쪽으로 올라간 상태로 버티기",
    "턱만 철봉 위로 넘기기",
    "내려오는 구간을 놓치기",
  ],
  stopSignals: GLOBAL_SAFETY_STOP_SIGNALS,
  doorframeBarChecklist: [
    "운동 전 문틈철봉 설치 상태를 확인한다.",
    "제품 허용하중을 확인한다.",
    "처음부터 점프해서 매달리지 않는다.",
    "발을 바닥에 둔 상태에서 서서히 하중을 걸어 흔들림을 확인한다.",
  ],
  expectedLevelRange: { first: 0, last: 8 },
  levels: [
    makeLevel({
      level: 0,
      key: "pull-0-foot-assisted-hang",
      name: "발 보조 매달리기",
      metricRule: durationRule(30, 30),
      targetLabel: formatUpperBodyTargetLabel(durationRule(30, 30)),
      restSeconds: 120,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "양발을 바닥에 두고 더 많은 체중을 발에 싣는다.",
      assessment: { eligible: true, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 1,
      key: "pull-1-dead-hang",
      name: "데드행",
      metricRule: durationRule(30, 45),
      targetLabel: formatUpperBodyTargetLabel(durationRule(30, 45)),
      restSeconds: 120,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "발 보조 매달리기로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 2,
      key: "pull-2-scapular-pull-up",
      name: "스캐풀라 풀업",
      metricRule: repsRule(8, 10, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(8, 10, "none")),
      restSeconds: 120,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "데드행 또는 발 보조 매달리기로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 3,
      key: "pull-3-foot-assisted-pull-up",
      name: "발 보조 풀업",
      metricRule: repsRule(8, 12, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(8, 12, "none")),
      restSeconds: 120,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "스캐풀라 풀업 또는 발 보조 매달리기로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 4,
      key: "pull-4-negative-pull-up",
      name: "네거티브 풀업",
      metricRule: tempoRepsRule(5, 5, 5),
      targetLabel: formatUpperBodyTargetLabel(tempoRepsRule(5, 5, 5)),
      restSeconds: 180,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "발 보조 풀업으로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 5,
      key: "pull-5-chin-up",
      name: "친업",
      metricRule: repsRule(5, 8, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(5, 8, "none")),
      restSeconds: 180,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "네거티브 풀업 또는 발 보조 풀업으로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 6,
      key: "pull-6-strict-pull-up",
      name: "정자세 풀업",
      metricRule: repsRule(5, 8, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(5, 8, "none")),
      restSeconds: 180,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "친업 또는 네거티브 풀업으로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 7,
      key: "pull-7-chest-to-bar",
      name: "체스트 투 바",
      metricRule: repsRule(5, 8, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(5, 8, "none")),
      restSeconds: 180,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "정자세 풀업 또는 친업으로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 8,
      key: "pull-8-archer-pull-up-progression",
      name: "아처 풀업 진행",
      metricRule: repsRule(3, 5, "perSide"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(3, 5, "perSide")),
      restSeconds: 180,
      equipment: DOORFRAME_BAR_EQUIPMENT,
      regression: "체스트 투 바 또는 정자세 풀업으로 낮춘다.",
      assessment: { eligible: false, ...BAR_CHECKLIST_GATE },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
  ],
} as const
