import { GLOBAL_SAFETY_STOP_SIGNALS } from "../content/common"
import { CategoryIdSchema } from "../schemas"
import {
  formatUpperBodyTargetLabel,
  repsRule,
  type UpperBodyCatalog,
  type UpperBodyExerciseLevel,
} from "./upper-body"

const PUSH_EQUIPMENT = ["맨몸", "푸시업바 선택 사용"] as const
const PUSH_REGRESSION = "현재 레벨보다 쉬운 푸시업으로 워밍업하거나 반복 수를 낮춰 자세를 유지한다."
const PUSH_RIR_ASSESSMENT = { min: 1, max: 2 } as const

const makeLevel = (level: UpperBodyExerciseLevel): UpperBodyExerciseLevel => level

export const PUSH_CATEGORY: UpperBodyCatalog = {
  id: CategoryIdSchema.parse("push"),
  title: "PUSH",
  muscles: ["가슴", "삼두", "전면 어깨"],
  longTermGoal: "일반 푸시업 → 디클라인 → 아처 → 원암 푸시업",
  warmup: [
    "팔 원 그리기: 작은 원 5회 + 큰 원 5회",
    "벽 슬라이드 8~10회",
    "스캐풀라 푸시업 8~10회",
    "현재 레벨보다 쉬운 푸시업 5~8회",
  ],
  instructions: [
    "머리부터 발끝까지 몸통 일직선을 유지한다.",
    "엉덩이가 과하게 내려가거나 올라가지 않게 유지한다.",
    "팔꿈치를 몸통과 완전히 90도로 벌리지 않는다.",
    "가슴이 바닥 쪽으로 내려가도록 통증 없는 범위에서 충분한 가동범위를 확보한다.",
    "올라올 때 허리가 먼저 꺾이지 않도록 복부와 둔근에 힘을 유지한다.",
  ],
  mistakes: [
    "목만 먼저 내려가기",
    "허리 꺾임",
    "반동 사용",
    "반복 수를 늘리려고 가동범위를 줄이기",
  ],
  stopSignals: GLOBAL_SAFETY_STOP_SIGNALS,
  expectedLevelRange: { first: 0, last: 7 },
  levels: [
    makeLevel({
      level: 0,
      key: "push-0-wall-push-up",
      name: "벽 푸시업",
      metricRule: repsRule(15, 15, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(15, 15, "none")),
      restSeconds: 60,
      equipment: PUSH_EQUIPMENT,
      regression: PUSH_REGRESSION,
      assessment: { eligible: true, rir: PUSH_RIR_ASSESSMENT },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 1,
      key: "push-1-high-incline-push-up",
      name: "높은 인클라인 푸시업",
      metricRule: repsRule(15, 15, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(15, 15, "none")),
      restSeconds: 90,
      equipment: PUSH_EQUIPMENT,
      regression: "벽 푸시업 또는 더 높은 지지면 인클라인 푸시업으로 낮춘다.",
      assessment: { eligible: true, rir: PUSH_RIR_ASSESSMENT },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 2,
      key: "push-2-low-incline-push-up",
      name: "낮은 인클라인 푸시업",
      metricRule: repsRule(12, 15, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(12, 15, "none")),
      restSeconds: 90,
      equipment: PUSH_EQUIPMENT,
      regression: "더 높은 지지면 인클라인 푸시업으로 낮춘다.",
      assessment: { eligible: true, rir: PUSH_RIR_ASSESSMENT },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 3,
      key: "push-3-standard-push-up",
      name: "일반 푸시업",
      metricRule: repsRule(10, 15, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(10, 15, "none")),
      restSeconds: 120,
      equipment: PUSH_EQUIPMENT,
      regression: "낮은 인클라인 푸시업으로 낮춘다.",
      assessment: { eligible: true, rir: PUSH_RIR_ASSESSMENT },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 4,
      key: "push-4-decline-push-up",
      name: "디클라인 푸시업",
      metricRule: repsRule(8, 12, "none"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(8, 12, "none")),
      restSeconds: 180,
      equipment: PUSH_EQUIPMENT,
      regression: "일반 푸시업으로 낮춘다.",
      assessment: { eligible: false },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 5,
      key: "push-5-archer-push-up",
      name: "아처 푸시업",
      metricRule: repsRule(5, 8, "perSide"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(5, 8, "perSide")),
      restSeconds: 180,
      equipment: PUSH_EQUIPMENT,
      regression: "디클라인 푸시업 또는 일반 푸시업으로 낮춘다.",
      assessment: { eligible: false },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 6,
      key: "push-6-assisted-one-arm-push-up",
      name: "보조 원암 푸시업",
      metricRule: repsRule(5, 8, "perSide"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(5, 8, "perSide")),
      restSeconds: 180,
      equipment: PUSH_EQUIPMENT,
      regression: "아처 푸시업 또는 디클라인 푸시업으로 낮춘다.",
      assessment: { eligible: false },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
    makeLevel({
      level: 7,
      key: "push-7-one-arm-push-up",
      name: "원암 푸시업",
      metricRule: repsRule(3, 5, "perSide"),
      targetLabel: formatUpperBodyTargetLabel(repsRule(3, 5, "perSide")),
      restSeconds: 180,
      equipment: PUSH_EQUIPMENT,
      regression: "보조 원암 푸시업 또는 아처 푸시업으로 낮춘다.",
      assessment: { eligible: false },
      instructions: [],
      mistakes: [],
      safety: [],
    }),
  ],
} as const
