import { CategoryIdSchema } from "../schemas"
import { defineCatalogCategory, PROGRESSION_RIR, STOP_SIGNALS } from "./lower-catalog.private"

const instructions = [
  "발바닥 전체가 바닥에 닿도록 유지한다.",
  "무릎은 발끝 방향과 비슷하게 움직인다.",
  "통증 없이 자세가 유지되는 깊이까지만 내려간다.",
] as const

const mistakes = [
  "무릎이 안쪽으로 심하게 무너짐",
  "허리를 억지로 세워 골반과 허리에 부담을 줌",
  "반복 수를 위해 깊이나 균형을 잃음",
] as const

const safety = [
  "날카로운 무릎 통증이나 갑작스러운 허리 통증이 있으면 해당 운동을 중단한다.",
] as const

export const squat = defineCatalogCategory({
  id: CategoryIdSchema.parse("squat"),
  title: "SQUAT",
  muscles: ["대퇴사두근", "둔근"],
  warmup: [
    "발목 무릎 밀기 좌우 10회",
    "골반 원 그리기 좌우 8회",
    "의자 스쿼트 또는 맨몸 스쿼트 8회",
    "바닥 자세에서 1초 멈추는 맨몸 스쿼트 5회",
  ],
  instructions,
  mistakes,
  stopSignals: STOP_SIGNALS,
  levels: [
    {
      level: 0,
      name: "의자 스쿼트",
      targetLabel: "15회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 15,
        max: 15,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 90,
      assessmentEligible: true,
      promotable: true,
      equipment: ["의자"],
      regressions: ["더 높은 의자에서 시작한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 1,
      name: "맨몸 스쿼트",
      targetLabel: "15~20회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 15,
        max: 20,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 90,
      assessmentEligible: true,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["의자 스쿼트로 깊이를 제한한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 2,
      name: "5kg 고블릿 스쿼트",
      targetLabel: "15회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 15,
        max: 15,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: true,
      promotable: true,
      equipment: ["5kg 덤벨 1개"],
      regressions: ["맨몸 스쿼트로 돌아가 자세를 유지한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 3,
      name: "10kg 덤벨 스쿼트",
      targetLabel: "12~15회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 12,
        max: 15,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 150,
      assessmentEligible: true,
      promotable: true,
      equipment: ["5kg 덤벨 2개"],
      regressions: ["5kg 고블릿 스쿼트로 중량을 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 4,
      name: "리버스 런지",
      targetLabel: "좌우 10~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 10,
        max: 12,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 150,
      assessmentEligible: false,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["보폭을 줄이고 의자나 벽을 가볍게 잡는다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 5,
      name: "불가리안 스플릿 스쿼트",
      targetLabel: "좌우 8~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 12,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["의자 또는 낮은 받침"],
      regressions: ["리버스 런지로 돌아가 좌우 균형을 확보한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 6,
      name: "덤벨 불가리안 스플릿 스쿼트",
      targetLabel: "좌우 8~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 12,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["의자 또는 낮은 받침", "5kg 덤벨"],
      regressions: ["맨몸 불가리안 스플릿 스쿼트로 중량을 뺀다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 7,
      name: "박스 피스톨 스쿼트",
      targetLabel: "좌우 5~8회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 5,
        max: 8,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["안정적인 의자 또는 박스"],
      regressions: ["더 높은 박스를 사용하거나 덤벨 없는 불가리안 단계로 돌아간다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 8,
      name: "피스톨 스쿼트",
      targetLabel: "좌우 5회 이상 × 3세트",
      metricRule: {
        kind: "reps",
        min: 5,
        max: 5,
        sets: 3,
        laterality: "perSide",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["박스 피스톨 스쿼트로 깊이를 제한한다."],
      instructions,
      mistakes,
      safety,
    },
  ],
} as const)
