import { CategoryIdSchema } from "../schemas"
import { defineCatalogCategory, PROGRESSION_RIR, STOP_SIGNALS } from "./lower-catalog.private"

const instructions = [
  "어깨와 손목 워밍업 후 통제 가능한 범위에서 수행한다.",
  "몸통 긴장을 유지하고 목만 먼저 내려가지 않게 한다.",
  "핸드스탠드 계열은 균형과 기술 요구가 크므로 속도를 늦춘다.",
] as const

const mistakes = [
  "허리가 과하게 꺾임",
  "어깨가 찌르는 각도를 억지로 통과함",
  "손목 불편감을 무시하고 반복함",
] as const

const safety = [
  "어깨가 걸리거나 찌르는 통증, 저림, 심한 어지럼증이 있으면 해당 운동을 중단한다.",
] as const

export const verticalPush = defineCatalogCategory({
  id: CategoryIdSchema.parse("verticalPush"),
  title: "VERTICAL PUSH",
  muscles: ["어깨", "삼두"],
  warmup: [
    "어깨 작은 원 5회",
    "어깨 큰 원 5회",
    "벽 슬라이드 8~10회",
    "스캐풀라 푸시업 8회",
    "손목 전후 체중 이동 8~10회",
    "현재 운동의 쉬운 버전 5회",
  ],
  instructions,
  mistakes,
  stopSignals: STOP_SIGNALS,
  levels: [
    {
      level: 0,
      name: "덤벨 숄더프레스",
      targetLabel: "8~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 12,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: true,
      promotable: true,
      equipment: ["5kg 덤벨 2개"],
      regressions: ["덤벨 한 개씩 번갈아 수행하거나 반복 수를 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 1,
      name: "높은 인클라인 파이크 푸시업",
      targetLabel: "10~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 10,
        max: 12,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: true,
      promotable: true,
      equipment: ["안정적인 높은 받침"],
      regressions: ["받침 높이를 높여 어깨 부하를 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 2,
      name: "파이크 푸시업",
      targetLabel: "8~12회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 8,
        max: 12,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: true,
      promotable: true,
      equipment: ["맨몸"],
      regressions: ["높은 인클라인 파이크 푸시업으로 돌아간다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 3,
      name: "발 높인 파이크 푸시업",
      targetLabel: "6~10회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 6,
        max: 10,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 120,
      assessmentEligible: false,
      promotable: true,
      equipment: ["안정적인 낮은 받침"],
      regressions: ["파이크 푸시업으로 발 높이를 제거한다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 4,
      name: "벽 핸드스탠드 홀드",
      targetLabel: "30~45초 × 3세트",
      metricRule: { kind: "duration", minSeconds: 30, maxSeconds: 45, sets: 3, laterality: "none" },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["벽", "미끄럽지 않은 바닥"],
      regressions: ["벽 워크 범위를 줄이거나 발 높인 파이크 푸시업으로 돌아간다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 5,
      name: "부분범위 벽 HSPU",
      targetLabel: "5~8회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 5,
        max: 8,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["벽", "미끄럽지 않은 바닥"],
      regressions: ["벽 핸드스탠드 홀드 또는 발 높인 파이크 푸시업으로 돌아간다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 6,
      name: "벽 HSPU",
      targetLabel: "5~8회 × 3세트",
      metricRule: {
        kind: "reps",
        min: 5,
        max: 8,
        sets: 3,
        laterality: "none",
        rir: PROGRESSION_RIR,
      },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["벽", "미끄럽지 않은 바닥"],
      regressions: ["부분범위 벽 HSPU로 가동범위를 줄인다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 7,
      name: "프리 핸드스탠드",
      targetLabel: "20~30초 × 3세트",
      metricRule: { kind: "duration", minSeconds: 20, maxSeconds: 30, sets: 3, laterality: "none" },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: true,
      equipment: ["넓고 미끄럽지 않은 공간"],
      regressions: ["벽 핸드스탠드 홀드로 균형 요구를 낮춘다."],
      instructions,
      mistakes,
      safety,
    },
    {
      level: 8,
      name: "프리 HSPU",
      targetLabel: "상급 목표",
      metricRule: { kind: "terminal", label: "상급 목표", laterality: "none" },
      restSeconds: 180,
      assessmentEligible: false,
      promotable: false,
      equipment: ["넓고 미끄럽지 않은 공간"],
      regressions: ["프리 핸드스탠드 또는 벽 HSPU로 돌아간다."],
      instructions,
      mistakes,
      safety,
    },
  ],
} as const)
